const STORAGE_KEY="opalday-data-v1",CODE_KEY="opalday-sync-code",DAY=86400000,OPALDAY_VERSION="1.3.3";
window.OPALDAY_VERSION=OPALDAY_VERSION;
const state={planner:normalize(load(STORAGE_KEY,{items:[],updatedAt:""})),syncCode:localStorage.getItem(CODE_KEY)||"",syncStatus:"Local only",saveTimer:null,view:"today",filter:"all",selectedId:null,editItemId:null};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],workerUrl=()=>(window.OPALDAY_CONFIG?.workerUrl||"").replace(/\/$/,"");
function load(k,f){try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}}
function canonicalizeSportsCalendars(p){
  const sports=[
    {id:"astros",name:"Houston Astros",aliases:["astros","houston astros"]},
    {id:"vgk",name:"Vegas Golden Knights",aliases:["vgk","golden knights","vegas golden knights"]},
    {id:"pwhl-vegas",name:"PWHL Las Vegas",aliases:["pwhl las vegas","pwhl vegas"]},
    {id:"boston-fleet",name:"Boston Fleet",aliases:["boston fleet"]},
    {id:"wpbl",name:"WPBL",aliases:["wpbl","women’s pro baseball","womens pro baseball"]}
  ];
  p.calendars=p.calendars||[];p.events=p.events||[];
  for(const sport of sports){
    const candidates=p.calendars.filter(calendar=>calendar?.sportId===sport.id||sport.aliases.includes(String(calendar?.name||"").trim().toLowerCase()));
    if(!candidates.length)continue;
    const eventCount=calendar=>p.events.filter(event=>event?.calendarId===calendar.id).length;
    candidates.sort((a,b)=>eventCount(b)-eventCount(a)||Number(String(b.name||"").trim().toLowerCase()===sport.name.toLowerCase())-Number(String(a.name||"").trim().toLowerCase()===sport.name.toLowerCase()));
    const keep=candidates[0],duplicateIds=new Set(candidates.slice(1).map(calendar=>calendar.id));
    keep.sportId=sport.id;keep.name=sport.name;keep.visible=candidates.some(calendar=>calendar.visible!==false);
    for(const event of p.events){
      if(duplicateIds.has(event.calendarId)||(event.source==="sports"&&event.sportId===sport.id))event.calendarId=keep.id;
    }
    if(duplicateIds.size)p.calendars=p.calendars.filter(calendar=>!duplicateIds.has(calendar.id));
  }
  return p;
}
function normalize(p){p||={items:[],updatedAt:""};p.items=(p.items||[]).map(i=>({target:1,cadence:"weekly",completions:[],subtasks:[],rescueReminder:true,...i,subtasks:(i.subtasks||[]).map(s=>({done:false,...s}))}));p.dayReminders=p.dayReminders||{};p.deletedItemIds=p.deletedItemIds||[];p.deletedEventIds=p.deletedEventIds||[];p.dismissedAllDayOccurrences=[...new Set(p.dismissedAllDayOccurrences||[])];return canonicalizeSportsCalendars(p)}
function uid(){return crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2)}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function randomCode(){const c="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";return Array.from({length:8},()=>c[Math.floor(Math.random()*c.length)]).join("")}
function parseEntry(value){const [rawTitle,rawSubs=""]=value.split(/:(.+)/);let title=rawTitle.trim(),lower=title.toLowerCase();const kind=/med|dose|injection|vyvgart|nucala/.test(lower)?"medication":/clean|tidy|organize|reset|sheets|closet|desk|table|shelf|room/.test(lower)?"reset":"habit";let cadence=/every day|daily|each day/.test(lower)?"daily":/month/.test(lower)?"monthly":"weekly";const target=Number(lower.match(/(\d+)\s*(?:x|times?)\s*(?:a|per|each)?\s*week/)?.[1]||1),intervalWeeks=Number(lower.match(/every\s+(\d+)\s+weeks?/)?.[1]||0)||null;if(intervalWeeks)cadence="interval";const days=["sunday","monday","tuesday","wednesday","thursday","friday","saturday"],fixedDay=days.findIndex(d=>lower.includes(d)),time=lower.match(/(?:at\s+)?(\d{1,2})(?::(\d{2}))?\s*(am|pm)/);let fixedTime=null;if(time){let h=Number(time[1]);if(time[3]==="pm"&&h<12)h+=12;if(time[3]==="am"&&h===12)h=0;fixedTime=String(h).padStart(2,"0")+":"+(time[2]||"00")}
title=title.replace(/\b(?:every day|daily|each day|once a week|every week|weekly|once a month|every month|monthly)\b/gi,"").replace(/\b\d+\s*(?:x|times?)\s*(?:a|per|each)?\s*week\b/gi,"").replace(/\bevery\s+\d+\s+weeks?\b/gi,"").replace(/\b(?:on\s+)?(?:sunday|monday|tuesday|wednesday|thursday|friday|saturday)s?\b/gi,"").replace(/\b(?:at\s+)?\d{1,2}(?::\d{2})?\s*(?:am|pm)\b/gi,"").replace(/\s+/g," ").trim()||rawTitle.trim();const subtasks=rawSubs.split(",").map(v=>v.trim()).filter(Boolean).map(title=>({id:uid(),title,done:false}));return{id:uid(),title,kind,cadence,target,intervalWeeks,fixedDay:fixedDay>=0?fixedDay:null,fixedTime,hardDate:null,subtasks,completed:false,completions:[],rescueReminder:true,createdAt:new Date().toISOString()}}
function cadenceLabel(i){if(i.cadence==="daily")return"Every day";if(i.cadence==="monthly")return"Once a month";if(i.cadence==="interval")return`Every ${i.intervalWeeks||1} weeks`;if(i.cadence==="once")return i.hardDate?new Date(i.hardDate+"T12:00:00").toLocaleDateString([],{month:"short",day:"numeric",year:"numeric"}):"One hard date";return i.target>1?`${i.target} times this week`:i.fixedDay!==null?`Every ${["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"][i.fixedDay]}`:"Once a week"}
function periodCount(i,now=new Date()){const ds=(i.completions||[]).map(v=>new Date(v)).filter(d=>!Number.isNaN(d.getTime()));if(i.cadence==="daily")return ds.filter(d=>dateKey(d)===dateKey(now)).length;if(i.cadence==="monthly")return ds.filter(d=>d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth()).length;if(i.cadence==="once")return ds.length;const s=new Date(now);s.setHours(0,0,0,0);s.setDate(s.getDate()-s.getDay());const e=new Date(s);e.setDate(e.getDate()+7);return ds.filter(d=>d>=s&&d<e).length}
function target(i){return i.cadence==="weekly"?(i.target||1):1}function complete(i,d=new Date()){return periodCount(i,d)>=target(i)}
function dateKey(d=new Date()){return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")}
function takenOn(i,d=new Date()){return(i.completions||[]).some(v=>dateKey(new Date(v))===dateKey(d))}
function medOccursOn(i,d=new Date()){if(i.kind!=="medication")return false;const day=new Date(d);day.setHours(12,0,0,0);if(i.cadence==="daily")return true;if(i.cadence==="once")return!i.hardDate||i.hardDate===dateKey(day);if(i.cadence==="weekly")return i.fixedDay===null||i.fixedDay===day.getDay();if(i.cadence==="monthly"){const anchor=new Date((i.hardDate||i.createdAt.slice(0,10))+"T12:00");return day.getDate()===anchor.getDate()}if(i.cadence==="interval"){const anchor=new Date((i.hardDate||i.createdAt.slice(0,10))+"T12:00"),days=Math.round((day-anchor)/DAY);return days>=0&&days%((i.intervalWeeks||1)*7)===0}return false}
function medState(i,d=new Date()){if(i.kind!=="medication"||!medOccursOn(i,d))return null;if(takenOn(i,d))return"taken";if(i.snoozedUntil&&new Date(i.snoozedUntil)>new Date())return"snoozed";if(!i.fixedTime)return"due";const due=new Date(dateKey(d)+"T"+i.fixedTime);return new Date()>due?"overdue":"scheduled"}
function itemComplete(i,d=new Date()){return i.kind==="medication"?takenOn(i,d):complete(i,d)}
function dueToday(i){if(i.kind==="medication")return medOccursOn(i,new Date())||takenOn(i,new Date());if(i.cadence==="once")return !i.hardDate||i.hardDate===new Date().toISOString().slice(0,10)||complete(i);if(i.cadence==="weekly"&&i.fixedDay!==null&&i.target===1)return i.fixedDay===new Date().getDay()||complete(i);return true}
function save(push=true){localStorage.setItem(STORAGE_KEY,JSON.stringify(state.planner));render();if(push&&state.syncCode){clearTimeout(state.saveTimer);state.saveTimer=setTimeout(syncPush,650)}}
function render(){$("#todayDate").textContent=new Intl.DateTimeFormat("en-US",{weekday:"long",month:"long",day:"numeric"}).format(new Date());document.body.classList.toggle("calendar-active",state.view==="calendar");$$(".view").forEach(v=>v.classList.add("hidden"));$("#"+state.view+"View").classList.remove("hidden");$("#progressCard").classList.toggle("hidden",state.view!=="habits");$$("[data-view]").forEach(b=>b.classList.toggle("selected",b.dataset.view===state.view));$("#syncText").textContent=state.syncCode?state.syncStatus:"Set up sync";$(".sync-dot").classList.toggle("active",!!state.syncCode);renderToday();renderSystems();renderProgress()}
function renderToday(){
  const due=state.planner.items.filter(dueToday),done=due.filter(i=>itemComplete(i)).length,total=due.length,pct=total?Math.round(done/total*100):0;
  $("#progressTitle").textContent=total?`${done} of ${total} complete`:"Your day is wide open";$("#progressNote").textContent=total?(pct===100?"That’s plenty for today.":"One thing at a time is plenty."):"Add your first habit, reset, or medication.";$("#progressNumber").textContent=pct+"%";$("#progressRing").style.setProperty("--progress",pct*3.6+"deg");
  const events=window.OpalDayCalendar?.todayEvents?.()||[],rows=due.map(item=>({type:"system",item,time:item.fixedTime||null})).concat(events.map(event=>({type:"event",event,time:event.time||null})));
  rows.sort((a,b)=>{const ao=a.type==="system"&&a.item.kind==="medication"&&medState(a.item)==="overdue",bo=b.type==="system"&&b.item.kind==="medication"&&medState(b.item)==="overdue";if(ao!==bo)return ao?-1:1;const ar=a.type==="event"&&!a.time?0:a.time?1:a.type==="system"&&a.item.kind==="medication"?2:3,br=b.type==="event"&&!b.time?0:b.time?1:b.type==="system"&&b.item.kind==="medication"?2:3;return ar-br||(a.time||"99:99").localeCompare(b.time||"99:99")});
  $("#items").innerHTML=rows.length?`<div class="timeline">${rows.map(row=>row.type==="event"?todayEventHtml(row.event):itemHtml(row.item)).join("")}</div>`:`<button class="empty-state" id="emptyAdd"><span class="empty-orb">＋</span><strong>Build today naturally</strong><span>Add an event, medication, habit, or household reset and it’ll appear here.</span></button>`;
  $("#emptyAdd")?.addEventListener("click",openAddItem);bindButtons()
}
function todayEventHtml(e){const api=window.OpalDayCalendar,color=api?.color?.(e)||"#7899b7",calendar=api?.calendarName?.(e.calendarId)||"Calendar",time=e.time?new Date("2000-01-01T"+e.time).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"}):"All day",yearly=e.calendarId==="birthdays"||e.recurrence==="yearly",dayLabel=api?.eventDayLabel?.(e,new Date())||"",attr=e.source==="builtin"?"":` data-open-today-event="${e.id}"`,dismiss=!e.time?`<button class="dismiss-all-day" data-dismiss-today-event="${escapeHtml(api?.dismissalKey?.(e)||"")}" aria-label="Dismiss ${escapeHtml(e.title)} for today">×</button>`:"";return`<article class="timeline-item kind-event today-calendar-event" style="--timeline-color:${color}"><div class="time-column">${time}</div><div class="timeline-rail"><span></span></div><div class="item-bubble"><span class="calendar-event-mark"></span><div class="item-content"><button class="item-main"${attr}><div class="item-title-row"><strong>${escapeHtml(e.title)}</strong></div><span class="cadence">${dayLabel?dayLabel+" · ":yearly?"Every year · ":e.end?"Until "+new Date("2000-01-01T"+e.end).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})+" · ":""}${escapeHtml(calendar)}</span></button></div>${dismiss}</div></article>`}
function itemHtml(i){const time=i.fixedTime?new Date("2000-01-01T"+i.fixedTime).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"}):"Anytime",done=itemComplete(i),status=medState(i);return`<article class="timeline-item kind-${i.kind} ${done?"is-complete":""} ${status?"med-"+status:""}"><div class="time-column">${time}</div><div class="timeline-rail"><span></span></div><div class="item-bubble"><button class="check-button" data-toggle-item="${i.id}">${done?"✓":""}</button><div class="item-content"><button class="item-main" data-open-item="${i.id}"><div class="item-title-row"><strong>${escapeHtml(i.title)}</strong><span class="kind-label">${i.kind}</span></div><span class="cadence">${i.kind==="medication"?(status==="overdue"?"OVERDUE · ":status==="snoozed"?"Snoozed · ":status==="taken"?"Taken · ":"Hard deadline · "):""}${cadenceLabel(i)}${i.kind==="medication"?"":" · "+periodCount(i)+"/"+target(i)+" this period"}</span></button>${i.subtasks.length?`<div class="subtasks">${i.subtasks.map(s=>`<button class="${s.done?"done":""}" data-item="${i.id}" data-subtask="${s.id}"><i>${s.done?"✓":""}</i>${escapeHtml(s.title)}</button>`).join("")}</div>`:""}</div></div></article>`}
function renderSystems(){const items=state.planner.items.filter(i=>state.filter==="all"||i.kind===state.filter);$("#systemList").innerHTML=items.length?items.map(i=>`<button class="system-card" data-open-item="${i.id}"><span class="system-icon kind-${i.kind}">${i.kind==="medication"?"✦":i.kind==="reset"?"⌂":"✓"}</span><span><strong>${escapeHtml(i.title)}</strong><small>${cadenceLabel(i)} · ${periodCount(i)}/${target(i)}</small></span><b>›</b></button>`).join(""):`<div class="small-empty">Nothing here yet.</div>`;bindButtons()}
function renderProgress(){const items=state.planner.items,done=items.filter(i=>complete(i)).length,checks=items.reduce((s,i)=>s+(i.completions||[]).length,0);$("#statsGrid").innerHTML=`<div><strong>${done}</strong><span>goals met now</span></div><div><strong>${checks}</strong><span>total check-ins</span></div><div><strong>${items.length}</strong><span>active systems</span></div>`;const weekly=items.filter(i=>i.cadence==="weekly"),hit=weekly.reduce((s,i)=>s+Math.min(periodCount(i),target(i)),0),goal=weekly.reduce((s,i)=>s+target(i),0);$("#weekPercent").textContent=(goal?Math.round(hit/goal*100):0)+"%";const sunday=new Date();sunday.setHours(0,0,0,0);sunday.setDate(sunday.getDate()-sunday.getDay());$("#weekBars").innerHTML=Array.from({length:7},(_,n)=>{const d=new Date(sunday);d.setDate(d.getDate()+n);const count=items.reduce((s,i)=>s+(i.completions||[]).filter(v=>dateKey(new Date(v))===dateKey(d)).length,0);return`<div><span style="--h:${Math.min(100,18+count*24)}%"></span><small>${["S","M","T","W","T","F","S"][n]}</small></div>`}).join("");const monthly=items.filter(i=>i.cadence==="monthly");$("#monthlyList").innerHTML=monthly.length?monthly.map(i=>`<button class="monthly-row" data-open-item="${i.id}"><span>${complete(i)?"✓":"○"}</span><strong>${escapeHtml(i.title)}</strong><small>${complete(i)?"Done":"Open"}</small></button>`).join(""):`<p class="modal-note">Add a monthly room reset and it’ll appear here.</p>`;bindButtons()}
function bindButtons(){$$("[data-toggle-item]").forEach(b=>b.onclick=()=>toggleItem(b.dataset.toggleItem));$$("[data-subtask]").forEach(b=>b.onclick=()=>toggleSubtask(b.dataset.item,b.dataset.subtask));$$("[data-open-item]").forEach(b=>b.onclick=()=>showItem(b.dataset.openItem));$$("[data-open-today-event]").forEach(b=>b.onclick=()=>window.OpalDayCalendar?.openEvent?.(b.dataset.openTodayEvent));$$("[data-dismiss-today-event]").forEach(b=>b.onclick=e=>{e.stopPropagation();dismissAllDayOccurrence(b.dataset.dismissTodayEvent)})}
function dismissAllDayOccurrence(key){if(!key)return;state.planner.dismissedAllDayOccurrences=[...new Set([...(state.planner.dismissedAllDayOccurrences||[]),key])];changed();toast("All-day event cleared for today")}
function toggleItem(id){const i=state.planner.items.find(i=>i.id===id);if(!i)return;if(i.kind==="medication"){if(takenOn(i))i.completions=i.completions.filter(v=>dateKey(new Date(v))!==dateKey());else i.completions.push(new Date().toISOString());i.snoozedUntil=null}else if(i.cadence==="daily"){const today=dateKey();if(complete(i))i.completions=i.completions.filter(v=>dateKey(new Date(v))!==today);else i.completions.push(new Date().toISOString());i.completed=complete(i)}else{if(complete(i))i.completions.pop();else i.completions.push(new Date().toISOString());i.completed=complete(i)}changed()}
function toggleSubtask(iid,sid){const s=state.planner.items.find(i=>i.id===iid)?.subtasks.find(s=>s.id===sid);if(!s)return;s.done=!s.done;changed()}
function changed(){state.planner.updatedAt=new Date().toISOString();save()}
function showItem(id){const i=state.planner.items.find(i=>i.id===id);if(!i)return;state.selectedId=id;$("#itemModalTitle").textContent=i.title;$("#itemModalBody").innerHTML=`<div class="detail-grid"><span>Schedule<strong>${cadenceLabel(i)}</strong></span><span>Current progress<strong>${periodCount(i)} / ${target(i)}</strong></span><span>Streak protection<strong>${i.rescueReminder?"Gentle reminder on":"Off"}</strong></span><span>Type<strong>${i.kind}</strong></span></div>${i.subtasks.length?`<div class="detail-subtasks">${i.subtasks.map(s=>`<span>${s.done?"✓":"○"} ${escapeHtml(s.title)}</span>`).join("")}</div>`:""}`;const ms=medState(i);$("#medicationActions").classList.toggle("hidden",i.kind!=="medication");if(i.kind==="medication")$("#itemModalBody").insertAdjacentHTML("afterbegin",`<div class="med-hard-status ${ms||"scheduled"}"><strong>${ms==="overdue"?"Medication overdue":ms==="taken"?"Medication taken":ms==="snoozed"?"Reminder snoozed":"Hard medication deadline"}</strong><span>${i.fixedTime?"Due at "+new Date("2000-01-01T"+i.fixedTime).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"}):"Exact time required"}</span></div>`);openModal("#itemModal")}
function openModal(s){$(s).classList.remove("hidden");setTimeout(()=>$(s+" textarea")?.focus(),50)}function closeModals(){$$(".modal-backdrop").forEach(m=>m.classList.add("hidden"))}function toast(t){$("#toast").textContent=t;$("#toast").classList.remove("hidden");setTimeout(()=>$("#toast").classList.add("hidden"),2200)}
function updateFields(){const c=$("#itemCadence").value,k=$("#itemKind").value;$("#targetField").classList.toggle("hidden",c!=="weekly");$("#intervalField").classList.toggle("hidden",c!=="interval");$("#dateField").classList.toggle("hidden",c!=="once"&&!(k==="medication"&&c==="interval"));$("#dayField").classList.toggle("hidden",!["weekly","interval"].includes(c))}
function populateEditor(i){$("#itemKind").value=i.kind;$("#itemCadence").value=i.cadence;$("#itemTarget").value=i.target||1;$("#itemInterval").value=i.intervalWeeks||4;$("#itemDay").value=i.fixedDay??"";$("#itemTime").value=i.fixedTime||"";$("#itemDate").value=i.hardDate||"";$("#scheduleEditor").classList.remove("hidden");updateFields()}
function resetItemForm(){state.editItemId=null;$("#itemFormEyebrow").textContent="Add anything";$("#itemFormTitle").textContent="What do you want to track?";$("#addSubmit").textContent="Add item";$("#naturalEntry").value="";$("#entryPreview").classList.add("hidden");$("#scheduleEditor").classList.add("hidden")}
function openAddItem(){resetItemForm();openModal("#addModal")}
function editSelectedItem(){const i=state.planner.items.find(x=>x.id===state.selectedId);if(!i)return;state.editItemId=i.id;$("#itemFormEyebrow").textContent="Edit system";$("#itemFormTitle").textContent="Update this entry";$("#addSubmit").textContent="Save changes";$("#naturalEntry").value=i.title+(i.subtasks?.length?": "+i.subtasks.map(s=>s.title).join(", "):"");$("#entryPreview").innerHTML=`<strong>${escapeHtml(i.title)}</strong><span>Change the details below without losing your history.</span>`;$("#entryPreview").classList.remove("hidden");populateEditor(i);closeModals();openModal("#addModal")}
function mergeById(remote=[],local=[]){const merged=new Map();for(const entry of remote)if(entry?.id)merged.set(entry.id,entry);for(const entry of local)if(entry?.id){const prior=merged.get(entry.id);merged.set(entry.id,prior&&entry.completions?{...prior,...entry,completions:[...new Set([...(prior.completions||[]),...(entry.completions||[])])]}:entry)}return[...merged.values()]}
function eventSyncKey(e){if(e.source==="sports")return"sports:"+(e.sportId||e.calendarId||"")+":"+(e.sportUid||[e.date,e.time,e.title].join("|"));if(e.feedUid)return"feed:"+(e.calendarId||"")+":"+e.feedUid;return"id:"+e.id}
function eventRecordScore(e){return(e.userEdited?4:0)+(e.notification?.enabled?2:0)+(e.notification?1:0)}
function mergeEvents(remote=[],local=[]){const merged=new Map();for(const event of [...remote,...local]){if(!event?.id)continue;const key=eventSyncKey(event),prior=merged.get(key);if(!prior){merged.set(key,event);continue}const preferred=eventRecordScore(event)>=eventRecordScore(prior)?event:prior,other=preferred===event?prior:event;merged.set(key,{...other,...preferred,notification:preferred.notification||other.notification})}return[...merged.values()]}
function mergePlannerCopies(local,remote){local=normalize(local);remote=normalize(remote);const deletedItemIds=[...new Set([...(remote.deletedItemIds||[]),...(local.deletedItemIds||[])])],deletedEventIds=[...new Set([...(remote.deletedEventIds||[]),...(local.deletedEventIds||[])])];return normalize({...remote,...local,items:mergeById(remote.items,local.items).filter(x=>!deletedItemIds.includes(x.id)),events:mergeEvents(remote.events||[],local.events||[]).filter(x=>!deletedEventIds.includes(x.id)),calendars:mergeById(remote.calendars||[],local.calendars||[]),feeds:mergeById(remote.feeds||[],local.feeds||[]),sports:{...(remote.sports||{}),...(local.sports||{})},dayReminders:{...(remote.dayReminders||{}),...(local.dayReminders||{})},dismissedAllDayOccurrences:[...new Set([...(remote.dismissedAllDayOccurrences||[]),...(local.dismissedAllDayOccurrences||[])])],deletedFeedUids:[...new Set([...(remote.deletedFeedUids||[]),...(local.deletedFeedUids||[])])],deletedItemIds,deletedEventIds,updatedAt:[remote.updatedAt,local.updatedAt].filter(Boolean).sort().at(-1)||new Date().toISOString()})}
async function syncPull(){if(!state.syncCode||!workerUrl())return;state.syncStatus="Syncing…";render();try{const r=await fetch(`${workerUrl()}/sync?code=${state.syncCode}`);if(r.status===404){state.syncStatus="Ready to sync";render();return}if(!r.ok)throw Error();state.planner=mergePlannerCopies(state.planner,(await r.json()).data);state.syncStatus="Synced just now";save(false);await syncPush()}catch{state.syncStatus="Saved on this device";render()}}
async function syncPush(){if(!workerUrl()){state.syncStatus="Worker URL needed";render();return}state.syncStatus="Syncing…";render();try{const r=await fetch(workerUrl()+"/sync",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:state.syncCode,data:state.planner})});if(!r.ok)throw Error();state.syncStatus="Synced just now"}catch{state.syncStatus="Saved on this device"}render()}
function showSync(){$("#syncHeading").textContent=state.syncCode?"Your sync code":"Keep every device together";$("#syncBody").innerHTML=state.syncCode?`<div class="code-display">${state.syncCode.slice(0,4)} ${state.syncCode.slice(4)}</div><p class="modal-note">Enter this code on your iPhone or iPad to open the same planner.</p><button class="primary full" id="copyCode">Copy code</button>`:`<p class="modal-note">Create a private code on your first device, then enter it on the other one.</p><button class="primary full" id="createCode">Create my sync code</button><div class="or-divider"><span>or</span></div><label class="code-input-label">I already have a code<input id="existingCode" maxlength="8" placeholder="ABCD1234"></label><button class="secondary full" id="connectCode">Connect this device</button>`;$("#copyCode")?.addEventListener("click",()=>navigator.clipboard.writeText(state.syncCode).then(()=>toast("Sync code copied")));$("#createCode")?.addEventListener("click",()=>connect(randomCode()));$("#connectCode")?.addEventListener("click",()=>connect($("#existingCode").value));openModal("#syncModal")}
function connect(code){const c=code.toUpperCase().replace(/[^A-Z2-9]/g,"").slice(0,8);if(c.length!==8)return toast("Enter all 8 characters");state.syncCode=c;localStorage.setItem(CODE_KEY,c);closeModals();syncPull()}
$("#addButton").onclick=openAddItem;$$(".view-add").forEach(b=>b.onclick=openAddItem);$("#syncButton").onclick=showSync;$("#settingsButton").onclick=()=>{window.OpalDayNotifications?.updateSettings();$("#settingsSyncStatus").textContent=state.syncCode?state.syncStatus:"Not connected";$("#aboutVersion").textContent=OPALDAY_VERSION;openModal("#settingsModal")};$("#openSyncSettings").onclick=()=>{closeModals();showSync()};$("#openAboutSettings").onclick=()=>{closeModals();openModal("#aboutModal")};$("#editItem").onclick=editSelectedItem;$$("[data-close]").forEach(b=>b.onclick=closeModals);$$(".modal-backdrop").forEach(m=>m.onclick=e=>{if(e.target===m)closeModals()});$$("[data-view]").forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render();window.scrollTo({top:0,behavior:"smooth"})});$$("[data-filter]").forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;$$("[data-filter]").forEach(x=>x.classList.toggle("selected",x===b));renderSystems()});$("#itemCadence").onchange=updateFields;$("#itemKind").onchange=updateFields;
$("#naturalEntry").oninput=e=>{const v=e.target.value.trim();$("#entryPreview").classList.toggle("hidden",!v);$("#scheduleEditor").classList.toggle("hidden",!v);if(v){const i=parseEntry(v);populateEditor(i);$("#entryPreview").innerHTML=`<strong>${escapeHtml(i.title)}</strong><span>Suggested: ${cadenceLabel(i)} · change anything below</span>`}};
$("#addForm").onsubmit=e=>{e.preventDefault();const v=$("#naturalEntry").value.trim();if(!v)return;const parsed=parseEntry(v),existing=state.editItemId?state.planner.items.find(x=>x.id===state.editItemId):null,i=existing||parsed,priorSubs=existing?.subtasks||[];i.title=parsed.title;i.kind=$("#itemKind").value;i.cadence=$("#itemCadence").value;i.target=Number($("#itemTarget").value)||1;i.intervalWeeks=Number($("#itemInterval").value)||4;i.fixedDay=$("#itemDay").value===""?null:Number($("#itemDay").value);i.fixedTime=$("#itemTime").value||null;i.hardDate=$("#itemDate").value||null;i.subtasks=parsed.subtasks.map(s=>{const old=priorSubs.find(x=>x.title.toLowerCase()===s.title.toLowerCase());return old?{...old,title:s.title}:s});if(!existing)state.planner.items.push(i);const edited=!!existing;resetItemForm();closeModals();changed();toast(edited?"Changes saved":"Added gently")};
$("#medTaken").onclick=()=>{if(!state.selectedId)return;const i=state.planner.items.find(x=>x.id===state.selectedId);if(i&&!takenOn(i))i.completions.push(new Date().toISOString());if(i){i.snoozedUntil=null;closeModals();changed();toast("Medication marked taken")}};$("#medSnooze").onclick=()=>{const i=state.planner.items.find(x=>x.id===state.selectedId);if(i){i.snoozedUntil=new Date(Date.now()+30*60000).toISOString();closeModals();changed();toast("Reminder snoozed 30 minutes")}};$("#medReschedule").onclick=()=>{const i=state.planner.items.find(x=>x.id===state.selectedId);if(i){const next=prompt("New date (YYYY-MM-DD)",i.hardDate||dateKey());if(next){i.hardDate=next;i.cadence="once";i.snoozedUntil=null;closeModals();changed();toast("Medication rescheduled")}}};$("#deleteItem").onclick=()=>{if(!state.selectedId)return;state.planner.deletedItemIds=[...new Set([...(state.planner.deletedItemIds||[]),state.selectedId])];state.planner.items=state.planner.items.filter(i=>i.id!==state.selectedId);state.selectedId=null;closeModals();changed();toast("System deleted")};document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")syncPull()});window.addEventListener("focus",syncPull);let renderedLocalDate=dateKey();setInterval(()=>{const currentLocalDate=dateKey();if(currentLocalDate!==renderedLocalDate){renderedLocalDate=currentLocalDate;render()}},60000);if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");render();if(state.syncCode)syncPull();
async function medicationNotice(i,label){const title=label+": "+i.title,body=i.fixedTime?"Scheduled for "+new Date("2000-01-01T"+i.fixedTime).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"}):"Medication needs your attention.";try{if("Notification"in window&&Notification.permission==="granted"&&"serviceWorker"in navigator){const reg=await navigator.serviceWorker.ready;await reg.showNotification(title,{body,icon:"./app-icon.png",tag:"opalday-med-"+i.id+"-"+dateKey(),renotify:true})}else toast(title)}catch{toast(title)}}
function checkMedicationReminders(){const now=new Date();state.planner.items.filter(i=>i.kind==="medication"&&medOccursOn(i,now)&&!takenOn(i,now)).forEach(i=>{if(i.snoozedUntil&&new Date(i.snoozedUntil)>now)return;const due=i.fixedTime?new Date(dateKey(now)+"T"+i.fixedTime):new Date(dateKey(now)+"T09:00"),mins=Math.floor((now-due)/60000);let bucket=null,label="Medication due";if(mins>=-60&&mins<-55){bucket="one-hour";label="Medication due in one hour"}else if(mins>=0&&mins<5){bucket="due";label="Medication due now"}else if(mins>=30&&mins<35){bucket="thirty-over";label="Medication overdue"}else if(mins>=60&&mins%60<5){bucket="over-"+Math.floor(mins/60);label="Medication overdue"}if(!bucket)return;i.noticeLog=i.noticeLog||{};const today=i.noticeLog[dateKey(now)]||[];if(today.includes(bucket))return;today.push(bucket);i.noticeLog[dateKey(now)]=today;medicationNotice(i,label);localStorage.setItem(STORAGE_KEY,JSON.stringify(state.planner))})}
// Background reminders are opt-in and are scheduled by the v0.7 notification service.
